### ISSUE TITLE
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by PuiziWan** [vuoristo/MMAML-Regression#1]
![微信图片_20201210184444](https://user-images.githubusercontent.com/34938120/101762026-d512d580-3b17-11eb-969f-03a938f7803a.png)
![微信图片_20201210184456](https://user-images.githubusercontent.com/34938120/101762033-d6dc9900-3b17-11eb-8693-d2c05ca6d6f5.png)

how can i solve this problem? thx

**Comment by vuoristo** [comment]
It's probably easiest to just comment out the line 43 in main where it calls `get_git_revision_hash`.
